server:
  port: 8080

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        oauth2: DEBUG
        autoconfigure: INFO

spring:
  application:
    name: iaoauthserverROPC
  main:
    allow-circular-references: true
  #    openfeign:
  #      oauth2:
  #        enabled: true
  #        clientRegistrationId: iaoauthserver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/oauth2/jwks

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test1
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    enabled: true
    cache: false
    check-template: true
    prefix: classpath:/templates/

base:
  url: http://localhost:8080


